const HOUSEHOLD_PRIVACY_NOTICE_VERSION = "2026-07-30-v2";

const HOUSEHOLD_PRIVACY_CONSENT_STATUS = {
  ACKNOWLEDGED: "ACKNOWLEDGED",
  DECLINED: "DECLINED",
  WITHDRAWN: "WITHDRAWN",
};

const HOUSEHOLD_PRIVACY_SYNC_STATUS = {
  PENDING: "PENDING",
  SYNCED: "SYNCED",
  FAILED: "FAILED",
  CONFLICT: "CONFLICT",
};

module.exports = {
  HOUSEHOLD_PRIVACY_NOTICE_VERSION,
  HOUSEHOLD_PRIVACY_CONSENT_STATUS,
  HOUSEHOLD_PRIVACY_SYNC_STATUS,
};
