const { ROLE_CODES } = require("../auth/auth.middleware");

const PRIORITY = {
  CRITICAL: "CRITICAL",
  WARNING: "WARNING",
  INFORMATIONAL: "INFORMATIONAL",
};

const IN_APP_POLICY = {
  MANDATORY: "MANDATORY",
  OPTIONAL: "OPTIONAL",
  NOT_APPLICABLE: "NOT_APPLICABLE",
};

const EMAIL_POLICY = {
  DEFAULT_ON: "DEFAULT_ON",
  OPTIONAL: "OPTIONAL",
  UNAVAILABLE: "UNAVAILABLE",
};

const DELIVERY_MODE = {
  IMMEDIATE: "IMMEDIATE",
  HOURLY_SUMMARY: "HOURLY_SUMMARY",
  DAILY_SUMMARY: "DAILY_SUMMARY",
  THRESHOLD: "THRESHOLD",
  SILENT_UI_FEEDBACK: "SILENT_UI_FEEDBACK",
};

const USER_CONFIGURABILITY = {
  NONE: "NONE",
  EMAIL_ONLY: "EMAIL_ONLY",
  ALL_SUPPORTED_CHANNELS: "ALL_SUPPORTED_CHANNELS",
};

const NOTIFICATION_POLICY_ROWS = [
  {
    ruleCode: "DISASTER_EVENT_UPDATE",
    roleCode: ROLE_CODES.BARANGAY,
    categoryCode: "DISASTER_COORDINATION",
    categoryLabel: "Disaster Coordination",
    priority: PRIORITY.CRITICAL,
    inAppPolicy: IN_APP_POLICY.MANDATORY,
    emailPolicy: EMAIL_POLICY.DEFAULT_ON,
    deliveryMode: DELIVERY_MODE.IMMEDIATE,
    userConfigurability: USER_CONFIGURABILITY.EMAIL_ONLY,
  },
  {
    ruleCode: "HOUSEHOLD_REGISTERED",
    roleCode: ROLE_CODES.BARANGAY,
    categoryCode: "EVACUEE_MANAGEMENT",
    categoryLabel: "Evacuee Management",
    priority: PRIORITY.INFORMATIONAL,
    inAppPolicy: IN_APP_POLICY.OPTIONAL,
    emailPolicy: EMAIL_POLICY.UNAVAILABLE,
    deliveryMode: DELIVERY_MODE.HOURLY_SUMMARY,
    userConfigurability: USER_CONFIGURABILITY.ALL_SUPPORTED_CHANNELS,
  },
  {
    ruleCode: "HOUSEHOLD_VERIFICATION",
    roleCode: ROLE_CODES.BARANGAY,
    categoryCode: "EVACUEE_MANAGEMENT",
    categoryLabel: "Evacuee Management",
    priority: PRIORITY.WARNING,
    inAppPolicy: IN_APP_POLICY.MANDATORY,
    emailPolicy: EMAIL_POLICY.OPTIONAL,
    deliveryMode: DELIVERY_MODE.IMMEDIATE,
    userConfigurability: USER_CONFIGURABILITY.EMAIL_ONLY,
  },
  {
    ruleCode: "EVACUEE_ATTENDANCE_UPDATE",
    roleCode: ROLE_CODES.BARANGAY,
    categoryCode: "EVACUEE_MANAGEMENT",
    categoryLabel: "Evacuee Management",
    priority: PRIORITY.INFORMATIONAL,
    inAppPolicy: IN_APP_POLICY.OPTIONAL,
    emailPolicy: EMAIL_POLICY.UNAVAILABLE,
    deliveryMode: DELIVERY_MODE.HOURLY_SUMMARY,
    userConfigurability: USER_CONFIGURABILITY.ALL_SUPPORTED_CHANNELS,
  },
  {
    ruleCode: "DISTRIBUTION_UPDATE",
    roleCode: ROLE_CODES.BARANGAY,
    categoryCode: "RELIEF_OPERATIONS",
    categoryLabel: "Relief Operations",
    priority: PRIORITY.INFORMATIONAL,
    inAppPolicy: IN_APP_POLICY.OPTIONAL,
    emailPolicy: EMAIL_POLICY.OPTIONAL,
    deliveryMode: DELIVERY_MODE.HOURLY_SUMMARY,
    userConfigurability: USER_CONFIGURABILITY.ALL_SUPPORTED_CHANNELS,
  },
  {
    ruleCode: "SYNC_CONFLICT",
    roleCode: ROLE_CODES.BARANGAY,
    categoryCode: "SYSTEM_OPERATIONS",
    categoryLabel: "System Operations",
    priority: PRIORITY.CRITICAL,
    inAppPolicy: IN_APP_POLICY.MANDATORY,
    emailPolicy: EMAIL_POLICY.DEFAULT_ON,
    deliveryMode: DELIVERY_MODE.IMMEDIATE,
    userConfigurability: USER_CONFIGURABILITY.EMAIL_ONLY,
  },
  {
    ruleCode: "SYSTEM_ANOMALY",
    roleCode: ROLE_CODES.BARANGAY,
    categoryCode: "SYSTEM_OPERATIONS",
    categoryLabel: "System Operations",
    priority: PRIORITY.CRITICAL,
    inAppPolicy: IN_APP_POLICY.MANDATORY,
    emailPolicy: EMAIL_POLICY.DEFAULT_ON,
    deliveryMode: DELIVERY_MODE.IMMEDIATE,
    userConfigurability: USER_CONFIGURABILITY.EMAIL_ONLY,
  },
  {
    ruleCode: "DISASTER_EVENT_CREATED",
    roleCode: ROLE_CODES.MSWDO,
    categoryCode: "DISASTER_MANAGEMENT",
    categoryLabel: "Disaster Management",
    priority: PRIORITY.WARNING,
    inAppPolicy: IN_APP_POLICY.MANDATORY,
    emailPolicy: EMAIL_POLICY.DEFAULT_ON,
    deliveryMode: DELIVERY_MODE.IMMEDIATE,
    userConfigurability: USER_CONFIGURABILITY.EMAIL_ONLY,
  },
  {
    ruleCode: "DISASTER_EVENT_UPDATE",
    roleCode: ROLE_CODES.MSWDO,
    categoryCode: "DISASTER_MANAGEMENT",
    categoryLabel: "Disaster Management",
    priority: PRIORITY.CRITICAL,
    inAppPolicy: IN_APP_POLICY.MANDATORY,
    emailPolicy: EMAIL_POLICY.DEFAULT_ON,
    deliveryMode: DELIVERY_MODE.IMMEDIATE,
    userConfigurability: USER_CONFIGURABILITY.EMAIL_ONLY,
  },
  {
    ruleCode: "HOUSEHOLD_REGISTERED",
    roleCode: ROLE_CODES.MSWDO,
    categoryCode: "EVACUEE_MANAGEMENT",
    categoryLabel: "Evacuee Management",
    priority: PRIORITY.INFORMATIONAL,
    inAppPolicy: IN_APP_POLICY.OPTIONAL,
    emailPolicy: EMAIL_POLICY.OPTIONAL,
    deliveryMode: DELIVERY_MODE.HOURLY_SUMMARY,
    userConfigurability: USER_CONFIGURABILITY.ALL_SUPPORTED_CHANNELS,
  },
  {
    ruleCode: "HOUSEHOLD_VERIFICATION",
    roleCode: ROLE_CODES.MSWDO,
    categoryCode: "EVACUEE_MANAGEMENT",
    categoryLabel: "Evacuee Management",
    priority: PRIORITY.WARNING,
    inAppPolicy: IN_APP_POLICY.MANDATORY,
    emailPolicy: EMAIL_POLICY.OPTIONAL,
    deliveryMode: DELIVERY_MODE.IMMEDIATE,
    userConfigurability: USER_CONFIGURABILITY.EMAIL_ONLY,
  },
  {
    ruleCode: "EVACUEE_ATTENDANCE_UPDATE",
    roleCode: ROLE_CODES.MSWDO,
    categoryCode: "EVACUEE_MANAGEMENT",
    categoryLabel: "Evacuee Management",
    priority: PRIORITY.INFORMATIONAL,
    inAppPolicy: IN_APP_POLICY.OPTIONAL,
    emailPolicy: EMAIL_POLICY.OPTIONAL,
    deliveryMode: DELIVERY_MODE.HOURLY_SUMMARY,
    userConfigurability: USER_CONFIGURABILITY.ALL_SUPPORTED_CHANNELS,
  },
  {
    ruleCode: "DISTRIBUTION_UPDATE",
    roleCode: ROLE_CODES.MSWDO,
    categoryCode: "RELIEF_OPERATIONS",
    categoryLabel: "Relief Operations",
    priority: PRIORITY.INFORMATIONAL,
    inAppPolicy: IN_APP_POLICY.OPTIONAL,
    emailPolicy: EMAIL_POLICY.OPTIONAL,
    deliveryMode: DELIVERY_MODE.HOURLY_SUMMARY,
    userConfigurability: USER_CONFIGURABILITY.ALL_SUPPORTED_CHANNELS,
  },
  {
    ruleCode: "SYNC_CONFLICT",
    roleCode: ROLE_CODES.MSWDO,
    categoryCode: "SYSTEM_OPERATIONS",
    categoryLabel: "System Operations",
    priority: PRIORITY.CRITICAL,
    inAppPolicy: IN_APP_POLICY.MANDATORY,
    emailPolicy: EMAIL_POLICY.DEFAULT_ON,
    deliveryMode: DELIVERY_MODE.IMMEDIATE,
    userConfigurability: USER_CONFIGURABILITY.EMAIL_ONLY,
  },
  {
    ruleCode: "SYSTEM_ANOMALY",
    roleCode: ROLE_CODES.MSWDO,
    categoryCode: "SYSTEM_OPERATIONS",
    categoryLabel: "System Operations",
    priority: PRIORITY.CRITICAL,
    inAppPolicy: IN_APP_POLICY.MANDATORY,
    emailPolicy: EMAIL_POLICY.DEFAULT_ON,
    deliveryMode: DELIVERY_MODE.IMMEDIATE,
    userConfigurability: USER_CONFIGURABILITY.EMAIL_ONLY,
  },
  {
    ruleCode: "LOW_STOCK",
    roleCode: ROLE_CODES.MAYOR,
    categoryCode: "RELIEF_OPERATIONS",
    categoryLabel: "Relief Operations",
    priority: PRIORITY.WARNING,
    inAppPolicy: IN_APP_POLICY.MANDATORY,
    emailPolicy: EMAIL_POLICY.OPTIONAL,
    deliveryMode: DELIVERY_MODE.THRESHOLD,
    userConfigurability: USER_CONFIGURABILITY.EMAIL_ONLY,
  },
  {
    ruleCode: "CRITICAL_STOCK",
    roleCode: ROLE_CODES.MAYOR,
    categoryCode: "RELIEF_OPERATIONS",
    categoryLabel: "Relief Operations",
    priority: PRIORITY.CRITICAL,
    inAppPolicy: IN_APP_POLICY.MANDATORY,
    emailPolicy: EMAIL_POLICY.DEFAULT_ON,
    deliveryMode: DELIVERY_MODE.THRESHOLD,
    userConfigurability: USER_CONFIGURABILITY.EMAIL_ONLY,
  },
  {
    ruleCode: "NEAR_EXPIRY_STOCK",
    roleCode: ROLE_CODES.MAYOR,
    categoryCode: "RELIEF_OPERATIONS",
    categoryLabel: "Relief Operations",
    priority: PRIORITY.WARNING,
    inAppPolicy: IN_APP_POLICY.MANDATORY,
    emailPolicy: EMAIL_POLICY.OPTIONAL,
    deliveryMode: DELIVERY_MODE.THRESHOLD,
    userConfigurability: USER_CONFIGURABILITY.EMAIL_ONLY,
  },
  {
    ruleCode: "EXPIRED_STOCK",
    roleCode: ROLE_CODES.MAYOR,
    categoryCode: "RELIEF_OPERATIONS",
    categoryLabel: "Relief Operations",
    priority: PRIORITY.CRITICAL,
    inAppPolicy: IN_APP_POLICY.MANDATORY,
    emailPolicy: EMAIL_POLICY.DEFAULT_ON,
    deliveryMode: DELIVERY_MODE.IMMEDIATE,
    userConfigurability: USER_CONFIGURABILITY.EMAIL_ONLY,
  },
  {
    ruleCode: "INVENTORY_INCIDENT",
    roleCode: ROLE_CODES.MAYOR,
    categoryCode: "RELIEF_OPERATIONS",
    categoryLabel: "Relief Operations",
    priority: PRIORITY.CRITICAL,
    inAppPolicy: IN_APP_POLICY.MANDATORY,
    emailPolicy: EMAIL_POLICY.DEFAULT_ON,
    deliveryMode: DELIVERY_MODE.IMMEDIATE,
    userConfigurability: USER_CONFIGURABILITY.EMAIL_ONLY,
  },
  {
    ruleCode: "DONATION_STOCK_UPDATE",
    roleCode: ROLE_CODES.MAYOR,
    categoryCode: "RELIEF_OPERATIONS",
    categoryLabel: "Relief Operations",
    priority: PRIORITY.INFORMATIONAL,
    inAppPolicy: IN_APP_POLICY.OPTIONAL,
    emailPolicy: EMAIL_POLICY.OPTIONAL,
    deliveryMode: DELIVERY_MODE.DAILY_SUMMARY,
    userConfigurability: USER_CONFIGURABILITY.ALL_SUPPORTED_CHANNELS,
  },
  {
    ruleCode: "DONATION_STOCK_ANOMALY",
    roleCode: ROLE_CODES.MAYOR,
    categoryCode: "RELIEF_OPERATIONS",
    categoryLabel: "Relief Operations",
    priority: PRIORITY.CRITICAL,
    inAppPolicy: IN_APP_POLICY.MANDATORY,
    emailPolicy: EMAIL_POLICY.DEFAULT_ON,
    deliveryMode: DELIVERY_MODE.IMMEDIATE,
    userConfigurability: USER_CONFIGURABILITY.EMAIL_ONLY,
  },
  {
    ruleCode: "DISTRIBUTION_UPDATE",
    roleCode: ROLE_CODES.MAYOR,
    categoryCode: "RELIEF_OPERATIONS",
    categoryLabel: "Relief Operations",
    priority: PRIORITY.INFORMATIONAL,
    inAppPolicy: IN_APP_POLICY.OPTIONAL,
    emailPolicy: EMAIL_POLICY.OPTIONAL,
    deliveryMode: DELIVERY_MODE.HOURLY_SUMMARY,
    userConfigurability: USER_CONFIGURABILITY.ALL_SUPPORTED_CHANNELS,
  },
  {
    ruleCode: "DISASTER_EVENT_UPDATE",
    roleCode: ROLE_CODES.MAYOR,
    categoryCode: "DISASTER_MONITORING",
    categoryLabel: "Disaster Monitoring",
    priority: PRIORITY.CRITICAL,
    inAppPolicy: IN_APP_POLICY.MANDATORY,
    emailPolicy: EMAIL_POLICY.DEFAULT_ON,
    deliveryMode: DELIVERY_MODE.IMMEDIATE,
    userConfigurability: USER_CONFIGURABILITY.EMAIL_ONLY,
  },
  {
    ruleCode: "EVACUATION_SUMMARY_REPORT",
    roleCode: ROLE_CODES.MAYOR,
    categoryCode: "DISASTER_MONITORING",
    categoryLabel: "Disaster Monitoring",
    priority: PRIORITY.INFORMATIONAL,
    inAppPolicy: IN_APP_POLICY.OPTIONAL,
    emailPolicy: EMAIL_POLICY.OPTIONAL,
    deliveryMode: DELIVERY_MODE.DAILY_SUMMARY,
    userConfigurability: USER_CONFIGURABILITY.ALL_SUPPORTED_CHANNELS,
  },
  {
    ruleCode: "SYSTEM_ANOMALY",
    roleCode: ROLE_CODES.MAYOR,
    categoryCode: "SYSTEM_MONITORING",
    categoryLabel: "System Monitoring",
    priority: PRIORITY.CRITICAL,
    inAppPolicy: IN_APP_POLICY.MANDATORY,
    emailPolicy: EMAIL_POLICY.DEFAULT_ON,
    deliveryMode: DELIVERY_MODE.IMMEDIATE,
    userConfigurability: USER_CONFIGURABILITY.EMAIL_ONLY,
  },
];

const NOTIFICATION_RULE_TARGETS = [
  {
    code: "LOW_STOCK",
    name: "Low Stock Alert",
    triggerType: "INVENTORY_STOCK_THRESHOLD",
    targetRoleCode: ROLE_CODES.MAYOR,
  },
  {
    code: "CRITICAL_STOCK",
    name: "Critical Stock Alert",
    triggerType: "INVENTORY_STOCK_THRESHOLD",
    targetRoleCode: ROLE_CODES.MAYOR,
  },
  {
    code: "NEAR_EXPIRY_STOCK",
    name: "Near Expiry Stock Alert",
    triggerType: "INVENTORY_EXPIRY",
    targetRoleCode: ROLE_CODES.MAYOR,
  },
  {
    code: "EXPIRED_STOCK",
    name: "Expired Stock Alert",
    triggerType: "INVENTORY_EXPIRY",
    targetRoleCode: ROLE_CODES.MAYOR,
  },
  {
    code: "INVENTORY_INCIDENT",
    name: "Inventory Incident Alert",
    triggerType: "INVENTORY_INCIDENT",
    targetRoleCode: ROLE_CODES.MAYOR,
  },
  {
    code: "DONATION_STOCK_UPDATE",
    name: "Donation Stock Update",
    triggerType: "DONATION_UPDATE",
    targetRoleCode: ROLE_CODES.MAYOR,
  },
  {
    code: "DONATION_STOCK_ANOMALY",
    name: "Donation Stock Anomaly",
    triggerType: "DONATION_ANOMALY",
    targetRoleCode: ROLE_CODES.MAYOR,
  },
  {
    code: "DISASTER_EVENT_CREATED",
    name: "Newly Created Disaster Event",
    triggerType: "DISASTER_EVENT_CREATED",
    targetRoleCode: ROLE_CODES.MSWDO,
  },
  {
    code: "DISASTER_EVENT_UPDATE",
    name: "Disaster Event Update",
    triggerType: "DISASTER_EVENT",
    targetRoleCode: ROLE_CODES.MSWDO,
  },
  {
    code: "DISTRIBUTION_UPDATE",
    name: "Distribution Update",
    triggerType: "DISTRIBUTION_UPDATE",
    targetRoleCode: ROLE_CODES.MSWDO,
  },
  {
    code: "HOUSEHOLD_REGISTERED",
    name: "Household Registration Update",
    triggerType: "HOUSEHOLD_REGISTRATION",
    targetRoleCode: ROLE_CODES.BARANGAY,
  },
  {
    code: "HOUSEHOLD_VERIFICATION",
    name: "Household Verification Update",
    triggerType: "HOUSEHOLD_VERIFICATION",
    targetRoleCode: ROLE_CODES.BARANGAY,
  },
  {
    code: "EVACUEE_ATTENDANCE_UPDATE",
    name: "Evacuee Attendance Update",
    triggerType: "EVACUEE_ATTENDANCE_UPDATE",
    targetRoleCode: ROLE_CODES.BARANGAY,
  },
  {
    code: "SYNC_CONFLICT",
    name: "Synchronization Conflict Alert",
    triggerType: "SYNC_CONFLICT",
    targetRoleCode: ROLE_CODES.BARANGAY,
  },
  {
    code: "SYSTEM_ANOMALY",
    name: "System Anomaly Alert",
    triggerType: "SYSTEM_ANOMALY",
    targetRoleCode: ROLE_CODES.BARANGAY,
  },
  {
    code: "EVACUATION_SUMMARY_REPORT",
    name: "Evacuation Monitoring Summary",
    triggerType: "EVACUATION_SUMMARY",
    targetRoleCode: ROLE_CODES.MAYOR,
  },
];

const getPolicyRowsForRole = (roleCode) =>
  NOTIFICATION_POLICY_ROWS.filter((row) => row.roleCode === roleCode);

const getPolicyRow = (ruleCode, roleCode) =>
  NOTIFICATION_POLICY_ROWS.find(
    (row) => row.ruleCode === ruleCode && row.roleCode === roleCode,
  ) || null;

const getPolicyRolesForRule = (ruleCode) =>
  NOTIFICATION_POLICY_ROWS.filter((row) => row.ruleCode === ruleCode).map((row) => row.roleCode);

module.exports = {
  PRIORITY,
  IN_APP_POLICY,
  EMAIL_POLICY,
  DELIVERY_MODE,
  USER_CONFIGURABILITY,
  NOTIFICATION_POLICY_ROWS,
  NOTIFICATION_RULE_TARGETS,
  getPolicyRow,
  getPolicyRowsForRole,
  getPolicyRolesForRule,
};
